version: '3'
services:
  app:
    container_name: docker-node-mysql
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:5.7.28
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: test1234
      DATABASE_HOST: mysql